name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Authenticate Docker to GCP
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Build Image
        run: docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/utils/vnv:$(git rev-parse --short HEAD) .

      - name: Tag Image
        if: github.event_name != 'pull_request'
        run: docker tag us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/utils/vnv:$(git rev-parse --short HEAD) us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/utils/vnv:latest
      
      - name: Push Image
        if: github.event_name != 'pull_request'
        run: docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/utils/vnv:latest